name: My first flow
on: [push, workflow_dispatch]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: List all files
        run: ls -a

      - name: Print Working Directory
        run: pwd

      - name: Check repo
        uses: actions/checkout@v7

      - name: List all files
        run: ls -a
      - name: Print workflow file contents
        run: cat ./.github/workflows/main.yml
